name: Entrenamiento y validación del modelo

on:
  push:
    branches: [develop]
  pull_request:
    branches: [main, staging]

jobs:
  train-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install dvc black

    - name: Ejecutar reentrenamiento
      run: python retrain_model.py

    - name: Aplicar formato con Black automáticamente
      run: black .
